apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mail
  template:
    metadata:
      labels:
        app: mail
    spec:
      containers:
      - name: mail
        image: ixdotai/smtp
        env:
        - name: SMARTHOST_ADDRESS
          valueFrom:
            secretKeyRef:
              name: mail-secrets
              key: smarthost_address
        - name: SMARTHOST_PORT
          valueFrom:
            secretKeyRef:
              name: mail-secrets
              key: smarthost_port
        - name: SMARTHOST_USER
          valueFrom:
            secretKeyRef:
              name: mail-secrets
              key: smarthost_user
        - name: SMARTHOST_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mail-secrets
              key: smarthost_password
        - name: SMARTHOST_ALIASES
          valueFrom:
            secretKeyRef:
              name: mail-secrets
              key: smarthost_aliases

---

apiVersion: v1
kind: Service
metadata:
  name: mail
spec:
  selector:
    app: mail
  ports:
    - protocol: TCP
      port: 25
      targetPort: 25
