apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
data:
  mysql_password: bXlzcC1wYXNzd29yZA==  # Base64 encoded password
  mysql_root_password: cm9vdC1wYXNzd29yZA==  # Base64 encoded root password

---

apiVersion: v1
kind: Secret
metadata:
  name: mail-secrets
type: Opaque
data:
  smarthost_address: c21hcnRob3N0LmV4YW1wbGUuY29t  # Base64 encoded smarthost address
  smarthost_port: NTg3  # Base64 encoded port
  smarthost_user: c21hcnR1c2Vy  # Base64 encoded user
  smarthost_password: c21hcnR1cGFzc3dvcmQ=  # Base64 encoded password
  smarthost_aliases: YWxpYXNzZXMuY29uZg==  # Base64 encoded aliases file contents
